
sudo: required

language: cpp

compiler:
  - gcc

addons:
    apt:
        sources:
          - ubuntu-toolchain-r-test
        
        packages:
          - libboost-all-dev
          - cmake
          - gcc-5
          - g++-5

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - wget https://github.com/arvidn/libtorrent/releases/download/libtorrent-1_1/libtorrent-rasterbar-1.1.0.tar.gz
  - tar -xzvf libtorrent-rasterbar-1.1.0.tar.gz
  - pushd libtorrent-rasterbar-1.1.0
  - ./configure CPPFLAGS="-std=c++11"
  - make
  - sudo make install
  - popd
  - wget https://github.com/miloyip/rapidjson/archive/v1.0.2.tar.gz -o rapidjson-1.0.2.tar.gz
  - tar -xzvf rapidjson-1.0.2.tar.gz
  - pushd rapidjson-1.0.2
  - cmake
  - make
  - sudo make install
  - popd

install:
  - ./bootstrap.sh
  - ./configure
  - make
