
PATH=%PATH%;D:\usr\msys2\mingw64\bin
export CXX=D:\\usr\\msys2\\mingw64\\bin\\g++.exe
export CXXFLAGS=-D_WIN32_WINNT=0x0600
export BOOSTLIB_SUFFIX=-mgw52-mt-1_59
export LDLIBS= -L D:\dev\libtorrent-rasterbar-1.0.5\src\.libs -L d:/dev/libjson -ltorrent-rasterbar -lwsock32 -lws2_32 -liconv -lssl -lcrypto
export INSTALLDIR=D:/home/athorcis/workspace/web/athorrent/bin

default:
	$(MAKE) $@

%:
	@$(MAKE) $@
